# Generated by Django 5.1 on 2024-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
