# Generated by Django 5.1 on 2024-10-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='название'),
        ),
    ]
