# Generated by Django 5.1 on 2024-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0003_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="name",
            field=models.CharField(
                help_text="Введите кличку собаки - родителя",
                max_length=100,
                verbose_name="Кличка",
            ),
        ),
    ]
