# Generated by Django 5.1 on 2024-10-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0004_alter_parent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="breed",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите породу собаки - родителя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_dogs",
                to="dogs.breed",
                verbose_name="Порода",
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="year_born",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Укажите год рождения собаки - родителя",
                null=True,
                verbose_name="Год рождения",
            ),
        ),
    ]
