# Generated by Django 4.2.2 on 2024-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_alt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="токен"
            ),
        ),
    ]
