# Использование образа Python 3.12, который поддерживает Poetry
FROM python:3.12-slim

# Установка poetry
RUN pip install poetry

# Создание директории приложения
WORKDIR /app

# Копирование pyproject.toml и poetry.lock
COPY pyproject.toml poetry.lock /app/

# Установка зависимостей Poetry
RUN poetry config virtualenvs.create false && \
    poetry install --no-dev

# Копирование остальных файлов проекта
COPY . /app

# Копирование .env файл (для использования docker-compose)
# COPY .env /app/.env

# Команда для запуска вашего приложения
CMD ["python", "main.py"]
